find_mentor/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main_web.urls", namespace='main_web')),
    
]

main_web/urls.py
from asyncio import tasks
from unicodedata import name
from django.urls import path,include
from . import views



app_name="mentor_links" #uniquly identifies these urls
urlpatterns = [
   # path("home_api",views.home_api,name="index"),
   # path("",views.home,name="home"),
   
   path("",views.home,name="home"),
   path("home",views.home,name="home"),
   path("signup",views.signup,name="signup"),
   path("signin",views.signin,name="signin"),
   path("signout",views.signout,name="signout"),
   path('superuser',views.dashboard,name="dashboard_super"),
   path('user',views.dashboard,name="dashboard_user"),
   
   path("uni",views.unis,name="uni"),
   path("about",views.about,name="about"),

   
   
   # #path("<str:name>", views.greet,name="greet"),  #adding a genral url
   

   # path("task",views.task,name="mentors"),
   # path("task",views.task,name="reviews"),



]

main_web/models.py
from asyncio import constants
from enum import unique
from pickle import FALSE
from xml.parsers.expat import model
from django.db import models

import django.contrib.auth.models  # importing authentable users table from posgresql, fyam_database

# Create your models here.

class University(models.Model):
   name=models.CharField(max_length=30)
   location=models.CharField(max_length=100)


class Gikians(models.Model):
   
   reg_no=models.IntegerField(primary_key=True )
  
   uni_id=models.ForeignKey(University,null=False,on_delete=models.CASCADE,to_field='id')
  
   username=models.CharField(max_length=50,unique=True,null=False)

   hash = models.CharField(max_length=200)
   
   email=models.EmailField(unique=True)
   
   name=models.CharField(max_length=20)
   
   year=models.IntegerField(null=False)
   
   faculty=models.CharField(max_length=10)

   role = models.CharField(max_length=10)

   def __int__(self):
       return self.reg_no

   def __str__(self) :
      return f"{self.reg_no} : {self.username}"

class Giki_socities(models.Model):
   
   reg_no=models.ForeignKey(Gikians,on_delete=models.CASCADE,to_field='reg_no')
   
   socities = models.CharField(max_length=30)
   

class Giki_teams(models.Model):
   reg_no=models.ForeignKey(Gikians,null=False,on_delete=models.CASCADE,to_field='reg_no')
  
   teams = models.CharField(max_length=30)
   

class Mentor(models.Model):
   reg_no=models.ForeignKey(Gikians,null=False,on_delete=models.CASCADE)

   year=models.IntegerField(null=False)
 

class Mentees(models.Model):

   reg=models.ForeignKey(Gikians,on_delete=models.CASCADE,null=False,related_name='reg_no_is')

   mentor_id=models.ForeignKey(Gikians,null=True,on_delete=models.CASCADE,to_field='reg_no',related_name='mentor_ids')
   
   year = models.IntegerField()


class Mentees_of_mentors(models.Model):
   reg=models.ForeignKey(Gikians,on_delete=models.CASCADE)

   men_id=models.ForeignKey(Gikians,null=True,on_delete=models.CASCADE,to_field='reg_no',related_name='men_ids')
  

class Mentor_skills(models.Model):

   reg=models.ForeignKey(Gikians,on_delete=models.CASCADE,to_field='reg_no')

   skills=models.CharField(max_length=40)

class Mentor_best_courses(models.Model):
   reg=models.ForeignKey(Gikians,on_delete=models.CASCADE,to_field='reg_no')
   
   best_courses=models.CharField(max_length=40)


class Mentees_weak_courses(models.Model):
   reg=models.ForeignKey(Gikians,on_delete=models.CASCADE,to_field='reg_no')

   weak_courses=models.CharField(max_length=40)

class Mentee_interests(models.Model):
   reg=models.ForeignKey(Gikians,on_delete=models.CASCADE,to_field='reg_no')
  
   interests = models.CharField(max_length=40)
   id = models.AutoField(primary_key=True,null=False)
   

main_web/forms.py
# from dataclasses import fields
# from pyexpat import model

# from django.forms import ModelForm
# from dataclasses import fields
# from inspect import Attribute
# from random import choices
# from select import select
# from tkinter import Widget
# from tkinter.tix import INTEGER
# from xml.dom.minidom import Attr
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate 
from django import forms
from django.utils.safestring import mark_safe

Uni_choices=[
   ('OTHER','OTHER'),
   ('GIKI','GIKI'),
]

class Newtaskform(forms.Form):
   task=forms.CharField(label="new task")
  # priority=forms.IntegerField(label="pri",min_value=1,max_value=7)
 

class Signupform(UserCreationForm):
      first_name=forms.CharField(max_length=200,     label="First Name")
      
      last_name=forms.CharField(max_length=200,label="Last Name") 
      
      email = forms.EmailField()
      
      university = forms.CharField(
         max_length=30,
         widget=forms.TextInput(attrs={'id': 'uni-input-field',})
         )
     

      apl_for=forms.CharField(widget=forms.RadioSelect(choices=[("Mentor","Mentor"),("Mentee","Mentee")]))

      reg_no=forms.IntegerField()


      year=forms.IntegerField(widget=forms.Select(choices=[("1","1st Year"),("2","2nd Year"),("3","3r Year"),("4","4th Year")]))
      
      faculty=forms.CharField(widget=forms.Select(choices=[
         ("FCSE","FCSE"),
         ("FME","FME"),
         ("FEE","FEE"),
         ("FCVE","FCVE"),
         ("MGS","MGS"),
         ("FMCE","FMCE"),
      ]))

      class Meta:
         model=User
         fields=["username","first_name","last_name","email","password1","password2","university","reg_no","year","faculty","apl_for"]
         

class Signinform(UserCreationForm):
   class Meta:
      model=User
      fields=["username","password"]

course_choices = [
   ('CS101','CS101'),
   ('CS131','CS131'),

]

class best_courses_form():
   course_1 = forms.CharField(widget=forms.Select(choices=[course_choices]))   

   course_2 = forms.CharField(widget=forms.Select(choices=[course_choices]))   

   course_3 = forms.CharField(widget=forms.Select(choices=[course_choices]))   

main_web/views.py
from django.shortcuts import render,redirect
from django.db import connection
from .forms import Signupform
from django.contrib.auth import login, authenticate,logout 
from django.contrib import  messages 




#     Create your views here.

def home(request):
   return render(request, "main_web/home.html")



def signup(request):

   form = Signupform()
   if request.method=="POST":
      form = Signupform(request.POST)
      
      if form.is_valid():
      
##################################################
         messages.success(request,"Account Created.")
         
         cursor = connection.cursor()
         try:
            cursor.execute("insert into main_web_gikians(reg_no,username,email,name,year,faculty,role,uni_id_id) values(%s,%s,%s,%s,%s,%s,%s,%s)",
            (form.data['reg_no'],form.data['username'],form.data['email'],
            form.data['first_name'] + form.data['last_name'],form.data['year'],form.data['faculty'],form.data['apl_for'],1,))
         
            connection.commit()
                  
         except Exception as e:
            cursor.close()


         form.save()

         return redirect("/signin")

      else:
         print(f"Account not Created.{ str(form.errors.as_text)}")
         messages.success(request,f"Account not Created.{ str(form.errors.items)}" )
        
         return redirect("/signup")

   else:
      form=Signupform()
   
   return render(request,"main_web/signup.html",{
      'form':form,
   })

def signin(request):
   
   if request.method=="POST": 
      username=request.POST['username']
      password=request.POST['password']
      
      user = authenticate(request,username=username,password=password)
       
      if user is not None:
         login(request, user)
         
         return redirect('/home')
         
      else:
         messages.success(request,"The UserName or Password was Incorrect.")
         return render(request,'registration/login.html')
  
   else:
      return render(request,"registration/login.html",{
      "status":"login" ,

      })

def signout(request):
   logout(request)
   return redirect("mentor_links:home")
      

def dashboard(request):
   c1 = connection.cursor()
   c2 = connection.cursor()
   c3 = connection.cursor()
   c4 = connection.cursor()
   c5 = connection.cursor()
   c6 = connection.cursor()
   c7 = connection.cursor()
   c8 = connection.cursor()
   c9 = connection.cursor()
   c10 = connection.cursor()
   c11 = connection.cursor()
   c12 = connection.cursor()
   c13 = connection.cursor()
   c14 = connection.cursor()
   c15 = connection.cursor()
   c16 = connection.cursor()
   
   try:
      c1.execute('select * from main_web_gikians', ['localhost'])
      c2.execute('select * from main_web_university',['localhost'])
      c3.execute('select * from main_web_giki_socities',['localhost'])
      c4.execute('select * from main_web_giki_teams',['localhost'])
      c5.execute('select * from main_web_mentor',['localhost'])
      c6.execute('select * from main_web_mentees_of_mentors',['localhost'])
      c7.execute('select * from main_web_mentor_skills',['localhost'])
      c8.execute('select * from main_web_mentor_best_courses',['localhost'])
      c9.execute('select * from main_web_mentees',['localhost'])
      c10.execute('select * from main_web_mentees_weak_courses',['localhost'])
      c11.execute('select * from main_web_mentee_interests',['localhost'])



      row1 = c1.fetchall()
      row2 = c2.fetchall() 
      row3 = c3.fetchall() 
      row4 = c4.fetchall() 
      row5 = c5.fetchall() 
      row6 = c6.fetchall() 
      row7 = c7.fetchall() 
      row8 = c8.fetchall() 
      row9 = c9.fetchall() 
      row10 = c10.fetchall() 
      row11 = c11.fetchall() 

   except Exception as e:
       c1.close()
       c2.close()
       c3.close()
       c4.close()
       c5.close()
       c6.close()
       c7.close()
       c8.close()
       c9.close()
       c10.close()
       c11.close()
      
   context = {
                "table1":row1,
                "table2":row2,
                "table3":row3,
                "table4":row4,
                "table5":row5,
                "table6":row6,
                "table7":row7,
                "table8":row8,
                "table9":row9,
                "table10":row10,
                "table11":row11,

       }


   user = request.user.username

   if request.user.is_superuser:

      print(f'{request.user.is_superuser} is super user')
      return render(request,'main_web/admin_dashboard.html',context)
      

   elif not request.user.is_superuser:

      try:
         c12.execute("select role from main_web_gikians where username = %s",(user,))
         print(user)
         row1 = c12.fetchone()
         
         print(f'role is:{row1}')
         connection.commit()
         
      except Exception as e:
         c12.close()
         print(f'exception is: {e}')
      
      if str.lower(row1[0]) == 'mentor':
         print("now")
##################################################
         if request.method=="POST":
            
            course_1 = request.POST['course_1']
            course_2 = request.POST['cours_2']
            course_3 = request.POST['course_3']

            team_1 = request.POST['team_1']
            team_2 = request.POST['team_2']
            team_3 = request.POST['team_3']
            
            socity_1 = request.POST['socity_1']
            socity_2 = request.POST['socity_2']
            socity_3 = request.POST['socity_3']

            skill_1 = request.POST['skill_1']
            skill_2 = request.POST['skill_2']
            skill_3 = request.POST['skill_3']

            # print(f'is123: {request.POST}')
            row13 = ''
            row14 = ''
            row15 = ''
            user = request.user.username
            print(f'user logged in is: {user}')

            try:


               c15.execute("""
               select main_web_gikians.reg_no as "gikians_reg_no",
		         main_web_gikians.name,main_web_gikians.year,main_web_gikians.faculty,
		         main_web_gikians.email
				
               from main_web_gikians

               where  	main_web_gikians.role = 'mentee' and

		         main_web_gikians.reg_no in (
                  select main_web_mentees_of_mentors.men_id_id from main_web_mentees_of_mentors, main_web_gikians
		            where main_web_gikians.username = %s
		            and main_web_gikians.reg_no = main_web_mentees_of_mentors.reg_id)
  
		         order by main_web_gikians.name;          
               
               """,(user,))
               row13 = c15.fetchall()
               print(f'query 13 is: {row13}')



               c14.execute('select main_web_gikians.reg_no from main_web_gikians where username = %s ',(request.user.username))
               
               reg_no = c14.fetchall() #reg_no
               


               c15.execute("insert into main_web_mentor_best_courses (best_courses,reg_id) values(%s,%s)"
               , (course_1,reg_no[0]))

               c15.execute("insert into main_web_mentor_best_courses (best_courses,reg_id) values(%s,%s)"
               , (course_2,reg_no[0]))
               
               c15.execute("insert into main_web_mentor_best_courses (best_courses,reg_id) values(%s,%s)"
               , (course_3,reg_no[0]))

               c15.execute("insert into main_web_giki_teams (teams,reg_no_id) values(%s,%s)"
               , (team_1,reg_no[0]))

               c15.execute("insert into main_web_giki_teams (teams,reg_no_id) values(%s,%s)"
               , (team_2,reg_no[0]))

               c15.execute("insert into main_web_giki_teams (teams,reg_no_id) values(%s,%s)"
               , (team_3,reg_no[0]))


               c15.execute("insert into main_web_giki_socities (socities,reg_no_id) values(%s,%s)"
               , (socity_1,reg_no[0]))

               c15.execute("insert into main_web_giki_socities (socities,reg_no_id) values(%s,%s)"
               , (socity_2,reg_no[0]))

               c15.execute("insert into main_web_giki_socities (socities,reg_no_id) values(%s,%s)"
               , (socity_3,reg_no[0]))


               c15.execute("insert into main_web_mentor_skills (skills,reg_id) values(%s,%s)"
               , (skill_1,reg_no[0]))

               c15.execute("insert into main_web_mentor_skills (skills,reg_id) values(%s,%s)"
               , (skill_2,reg_no[0]))
            
         

               c15.execute("insert into main_web_mentor_skills (skills,reg_id) values(%s,%s)"
               , (skill_3,reg_no[0]))

               connection.commit()
          
            except Exception as e:
               
               c13.close()
               c14.close()
               c15.close()
               c16.close()


            print('mentor 1 login')
            # return redirect("/main_web/dashboard_user",{"mentee":row13,})
            return render(request,'main_web/user_dashboard_mentor.html',{
              "mentee":row13,
              "username":request.user.username,
             })
            
         else:
             return render(request,'main_web/user_dashboard_mentor.html',{"username":request.user.username,})
        
##################################################




      elif str.lower(row1[0]) == 'mentee':
         
         if request.method=="POST":
            
            course_1 = request.POST['course_1']
            course_2 = request.POST['cours_2']
            course_3 = request.POST['course_3']

            team_1 = request.POST['team_1']
            team_2 = request.POST['team_2']
            team_3 = request.POST['team_3']
            
            socity_1 = request.POST['socity_1']
            socity_2 = request.POST['socity_2']
            socity_3 = request.POST['socity_3']

            skill_1 = request.POST['skill_1']
            skill_2 = request.POST['skill_2']
            skill_3 = request.POST['skill_3']

            # print(f'is123: {request.POST}')
            row13 = ''

main_web/templates/main_web/about.html
<!-- {%load static%} -->
<!DOCTYPE html>
<html lang="en">
<head>
   <link rel="stylesheet" type="text/css" href="{% static 'main_web/css/bootstrap.css' %}">
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Find YourSelf A Mentor</title>
   
       <!-- <link rel="stylesheet" href="{% static 'main_web/layoutsss.css'%}"> -->
   <link rel="stylesheet" href="{% static 'main_web/layout02.css' %}">
      
   <link rel="stylesheet" href="{% static 'main_web/buttons.css' %}">
   
   <link rel="stylesheet" href="{% static 'main_web/birds.css' %}">

      <!-- <link rel="stylesheet" href="{% static 'main_web/buttons2.css' %}"> -->

      <!-- <script src="{% static '/js/js01.js' %}" type="text/javascript"></script> -->


      <style>
         body,html{
            overflow-y:auto;
            display:block;
            background-color: none;
         }

         .uni1{
            background-image: url('picture1.jpg');
            top: 10%;
            border: 2px solid black;
            width: 700px;
            height: 200px;
            border-radius: 5px;
         }
         .centre{
            margin-top: 200px;
            /* top: 10%; */
            display: flex;
            justify-content: center;
            align-items: center;
         }
      </style>
   



</head>
<body>
     



      <div class="main-container">
          <header class="main-header">
            <nav class="" id="navbar">
        
         <a class="btn1 btn-2" id="home_button" href="{% url 'mentor_links:home'%}"> Home</a>
        
         <a id="university-button" class="btn1 btn-2" href="{% url 'mentor_links:uni'%}"> Universities</a>
        
         <a class="btn1 btn-2" href="{% url 'mentor_links:about'%}"> About</a>
         
         
         {%if user.is_authenticated%}
            {%if user.is_superuser%}
               <a id="reviews-button" class="btn1 btn-2" href="{% url 'mentor_links:dashboard_super'%}"> {{user.username}}</a>
               
            {%else%}
               <a id="reviews-button" class="btn1 btn-2" href="{% url 'mentor_links:dashboard_user'%}"> {{user.username}}</a>

            {%endif%}
            
         
         {%endif%}
         
         {%if user.is_authenticated%} 
         <a id="signup-button" class="btn btn-1" href="{%url 'mentor_links:signout' %}">
            <svg>
               <rect x="0" y="0" fill="none" width="100%" height="100%"/>
            </svg>
            LogOut
        </a>
         {%else%}
         <a id="signup-button" class="btn btn-1" href="{% url 'mentor_links:signin'%}">
            <svg>
               <rect x="0" y="0" fill="none" width="100%" height="100%"/>
            </svg>
            Login 
            <!-- {{status}} -->
        </a>
         {%endif%} 
        


              </nav>
         </header>
  
         <div class="centre">

            <div class="uni1">
               Finding a Mentor is our 4th semester project for the course of DBMS. 
               This website is aimed at closing the mentoring gap and drive equity through quality mentoring for students. We are connecting and fueling opportunities for students at campus. Solve your problems with leading mentors at your side! We our on a mission to help students maximize their academic success and fulfillment.  
               Become a mentor and get a chance to gain a certificate from your respective institute, provided by Finding a Mentor. It will serve as a platform to connect students and professionals around the campus and create an ecosystem of opportunities.  
               
            </div>

         </div>
            


      </div>

  

</body>
</html>

main_web/templates/main_web/home.html
{% extends "main_web/layout.html"  %}



{% block center_body %}


<section class="border1" id="home_section">
   <div class="info border1">
      <div class="nine">
         <h1 id="heading1">Looking for a mentor?
            <span id="para">
               Here you'll find the best mentor suitable for your purposes and ambitions. we have all the qualified Mentors registered with us, that'll help you throughout your journey.
            </span>
         </h1>
       
      </div>
    
   </div>

   <div class="div-for-boxes">
      <div class="boxes border1">
         
         
         <div class="box-2">
            <div class="btn2 btn-two">
              <span>
               <a href="{% url 'mentor_links:signup'%}" id="find-mentor-txt">  Find A Mentor</a>
              </span>
            </div>
          </div>
   
          <div class="box-2">
            <div class="btn2 btn-two">
              <span>
               <a href="{% url 'mentor_links:signup'%}" id="become-mentor-txt">Become A Mentor</a>
              </span>
            </div>
          </div>
         
      
      </div>
   </div>
</section>



{% endblock %}

main_web/templates/main_web/index.html
{% extends "main_web/layout.html" %}

{% block section%}
   
   <ul>
   {%for i in tasks%}
      <li>{{i}}</li>
   {%endfor%}
</ul>
<a href="{% url 'mentor_links:tasks'%}">goto tasks page</a>

{%endblock%}

main_web/templates/main_web/layout.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
   <head>
   <link rel="stylesheet" type="text/css" href="{% static 'main_web/css/bootstrap.css' %}">
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Find YourSelf A Mentor</title>
   
       <!-- <link rel="stylesheet" href="{% static 'main_web/layoutsss.css'%}"> -->
   <link rel="stylesheet" href="{% static 'main_web/layout02.css' %}">
      
   <link rel="stylesheet" href="{% static 'main_web/buttons.css' %}">
   
   <link rel="stylesheet" href="{% static 'main_web/birds.css' %}">

      <!-- <link rel="stylesheet" href="{% static 'main_web/buttons2.css' %}"> -->

      <!-- <script src="{% static '/js/js01.js' %}" type="text/javascript"></script> -->


      <style>
         body,html{
            overflow-y:auto;
         }
      </style>
   
</head>
<body>
   
    <div class="" style="position: relative;min-height: 35rem;">
	
      
         <div class="bird-container bird-container--one">
            <div class="bird bird--one"></div>
         </div>
         
         <div class="bird-container bird-container--two">
            <div class="bird bird--two"></div>
         </div>
         
         <div class="bird-container bird-container--three">
            <div class="bird bird--three"></div>
         </div>
         
         <div class="bird-container bird-container--four">
            <div class="bird bird--four"></div>
         </div>
         
      </div>

   
   <div class="main-container">
      <header class="main-header">
         <nav class="" id="navbar">
           
            <a class="btn1 btn-2" id="home_button" href="{% url 'mentor_links:home'%}"> Home</a>
           
            <a id="university-button" class="btn1 btn-2" href="{% url 'mentor_links:uni'%}"> Universities</a>
           
            <a class="btn1 btn-2" href="{% url 'mentor_links:about'%}"> About</a>
            
            
            {%if user.is_authenticated%}
               {%if user.is_superuser%}
                  <a id="reviews-button" class="btn1 btn-2" href="{% url 'mentor_links:dashboard_super'%}"> {{user.username}}</a>
                  
               {%else%}
                  <a id="reviews-button" class="btn1 btn-2" href="{% url 'mentor_links:dashboard_user'%}"> {{user.username}}</a>

               {%endif%}
               
            
            {%endif%}
            
            {%if user.is_authenticated%} 
            <a id="signup-button" class="btn btn-1" href="{%url 'mentor_links:signout' %}">
               <svg>
                  <rect x="0" y="0" fill="none" width="100%" height="100%"/>
               </svg>
               LogOut
           </a>
            {%else%}
            <a id="signup-button" class="btn btn-1" href="{% url 'mentor_links:signin'%}">
               <svg>
                  <rect x="0" y="0" fill="none" width="100%" height="100%"/>
               </svg>
               Login 
               <!-- {{status}} -->
           </a>
            {%endif%} 
           


         </nav>
      </header>
     


      {%block center_body%}
      {%endblock%}

   <!-- 
      {% if name%}
      <h1> hello, {{name}}</h1>
      {%else %}
      <h1>hello random person</h1>
      {%endif%} -->

   </div>


</body>
</html>

main_web/templates/main_web/uni.html
<!-- {%load static%} -->
<!DOCTYPE html>
<html lang="en">
<head>
   <link rel="stylesheet" type="text/css" href="{% static 'main_web/css/bootstrap.css' %}">
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Find YourSelf A Mentor</title>
   
       <!-- <link rel="stylesheet" href="{% static 'main_web/layoutsss.css'%}"> -->
   <link rel="stylesheet" href="{% static 'main_web/layout02.css' %}">
      
   <link rel="stylesheet" href="{% static 'main_web/buttons.css' %}">
   
   <link rel="stylesheet" href="{% static 'main_web/birds.css' %}">

      <!-- <link rel="stylesheet" href="{% static 'main_web/buttons2.css' %}"> -->

      <!-- <script src="{% static '/js/js01.js' %}" type="text/javascript"></script> -->


      <style>
         body,html{
            overflow-y:auto;
            display:block;
            background-color: none;
         }

         .uni1{
            background-image: url('picture1.jpg');
            top: 10%;
            border: 2px solid black;
            width: 700px;
            height: 200px;
            border-radius: 5px;
         }
         .centre{
            margin-top: 200px;
            /* top: 10%; */
            display: flex;
            justify-content: center;
            align-items: center;
         }
      </style>
   



</head>
<body>
     



      <div class="main-container">
          <header class="main-header">
            <nav class="" id="navbar">
        
         <a class="btn1 btn-2" id="home_button" href="{% url 'mentor_links:home'%}"> Home</a>
        
         <a id="university-button" class="btn1 btn-2" href="{% url 'mentor_links:uni'%}"> Universities</a>
        
         <a class="btn1 btn-2" href="{% url 'mentor_links:about'%}"> About</a>
         
         
         {%if user.is_authenticated%}
            {%if user.is_superuser%}
               <a id="reviews-button" class="btn1 btn-2" href="{% url 'mentor_links:dashboard_super'%}"> {{user.username}}</a>
               
            {%else%}
               <a id="reviews-button" class="btn1 btn-2" href="{% url 'mentor_links:dashboard_user'%}"> {{user.username}}</a>

            {%endif%}
            
         
         {%endif%}
         
         {%if user.is_authenticated%} 
         <a id="signup-button" class="btn btn-1" href="{%url 'mentor_links:signout' %}">
            <svg>
               <rect x="0" y="0" fill="none" width="100%" height="100%"/>
            </svg>
            LogOut
        </a>
         {%else%}
         <a id="signup-button" class="btn btn-1" href="{% url 'mentor_links:signin'%}">
            <svg>
               <rect x="0" y="0" fill="none" width="100%" height="100%"/>
            </svg>
            Login 
            <!-- {{status}} -->
        </a>
         {%endif%} 
        


              </nav>
         </header>
  
         <div class="centre">

            <div class="uni1">
               The Ghulam Ishaq Khan Institute of Engineering Sciences and Technology (GIKI), is a private research university located in Topi, Khyber Pakhtunkhwa in Pakistan.
               It was founded by the former President of Pakistan, Ghulam Ishaq Khan, in 1993. Since its establishment, the institute has consistently attracted the country's most influential scientists such as Abdul Qadeer Khan, Asghar Qadir, and Shaukat Hameed Khan, who played a role in elevating the institute as one of world's finest science and engineering college. GIKI is known to be a competitive institution with a low acceptance rate requiring students to show extraordinary academic excellence and capabilities with strong financial footing to be accommodated.
                
               
            </div>

         </div>
            


      </div>

  

</body>
</html>